// Generates docs/pin-sweep.md: which pin-to-pin connections the rules reveal, which are allowed, and which are silent gaps. Run: npm run sweep
import { writeFileSync, mkdirSync } from 'node:fs';
import { registry, templates } from '../src/data';
import { runPinSweep, allPairKinds, KNOWN_GAPS } from '../src/eval/sweep';
export function renderReport(): string {

const lines: string[] = ['# Pin-to-pin connection coverage', '', 'Generated by `npm run sweep` (the test suite fails if this file is stale). Every pin was connected to every other pin, one pair at a time, in two ways: **fresh**, where both pins are first taken off their nets and joined alone, which answers what the pair itself reveals; and **merge**, where the pins are joined as the app does it and their existing nets merge, which is what a user experiences.', '',
  '**Basis.** Expectations come from the KiCad default ERC pin-type matrix (the industry list of which pin electrical types may share a net), plus domain rules for what that matrix cannot express: shorts to ground and motors that need a driver. **This is best effort, and honest about it.** *Covered* means every tested pair of that kind produced a violation or warning. *Allowed* means KiCad calls the pairing OK; a domain rule may still fire (voltage range, enable state, undriven net) and when it does it names one of the two pins, which the fresh column shows as fired (relevant). A firing that names neither pin would be noise and fails the test. *Gap* means KiCad calls it OK but a domain expert would still question it and no rule models it yet; the reason is in the last column. The coverage panel in the app lists evaluated dimensions for the same reason: a clean findings list only speaks for what was checked.', ''];
const exercised = new Set<string>();
for (const t of templates) {
  const fresh = runPinSweep(t, registry, 'fresh'); const merge = runPinSweep(t, registry, 'merge');
  for (const s of fresh.summary) exercised.add(s.key);
  const count = (v: string) => fresh.summary.filter((s) => s.verdict === v).length;
  lines.push(`## ${t.title}`, '', `${fresh.cases.length} pin pairs (fresh) · ${count('covered')} covered kinds · ${count('allowed')} allowed kinds · ${count('gap')} gap kinds · ${count('MISSED')} missed · ${count('NOISY')} noisy`, '',
    '| Pin roles | KiCad | Expectation | Pairs | Fresh: fired (relevant) | Merge: fired | Verdict | Why |', '| --- | --- | --- | --- | --- | --- | --- | --- |');
  for (const s of fresh.summary) { const m = merge.summary.find((x) => x.key === s.key); lines.push(`| ${s.key.replace('+', ' to ')} | ${s.kicad} | ${s.expectation} | ${s.tested} | ${s.fired} (${s.relevant}) | ${m ? `${m.fired}/${m.tested}` : '—'} | ${s.verdict} | ${s.why} |`); }
  lines.push('');
}
const untested = allPairKinds().filter((k) => !exercised.has(k));
lines.push('## Pair kinds no template exercises', '', 'These role pairs do not occur between any two parts in the current templates, so the sweep says nothing about them. They are neither covered nor allowed: untested.', '', untested.map((k) => `- ${k.replace('+', ' to ')}${KNOWN_GAPS[k] ? ` (known gap: ${KNOWN_GAPS[k]})` : ''}`).join('\n'), '');
return lines.join('\n');
}
if (process.argv[1]?.endsWith('pin-sweep.ts')) { mkdirSync('docs', { recursive: true }); writeFileSync('docs/pin-sweep.md', renderReport()); console.log('wrote docs/pin-sweep.md'); }
